products:
  - code: "87"
    description: "ABACAXI"
    unidade_comercial: "UN"
  - code: "34"
    description: "ABOB ITALIANA"
    unidade_comercial: "KG"
  - code: "37"
    description: "ABOBORA MORANGA"
    unidade_comercial: "KG"
  - code: "263"
    description: "AGUA MINERAL IG 20L"
    unidade_comercial: "UN"
  - code: "4"
    description: "ALFACE AMERICANA"
    unidade_comercial: "UN"
  - code: "782"
    description: "ALFACE AMERIC KG"
    unidade_comercial: "KG"
  - code: "490"
    description: "ALFACE KG"
    unidade_comercial: "KG"
  - code: "28"
    description: "ALFACE ROXA"
    unidade_comercial: "UN"
  - code: "781"
    description: "ALFACE ROXA KG"
    unidade_comercial: "KG"
  - code: "3"
    description: "ALFACE UNI"
    unidade_comercial: "UN"
  - code: "30"
    description: "ALHO COM CASCA"
    unidade_comercial: "KG"
  - code: "468"
    description: "ALHO PORO"
    unidade_comercial: "UN"
  - code: "31"
    description: "ALHO SEM CASCA"
    unidade_comercial: "KG"
  - code: "7"
    description: "ALMEIRAO"
    unidade_comercial: "KG"
  - code: "95"
    description: "BANANA CATURRA"
    unidade_comercial: "KG"
  - code: "97"
    description: "BANANA MACA"
    unidade_comercial: "KG"
  - code: "43"
    description: "BATATA DOCE"
    unidade_comercial: "KG"
  - code: "39"
    description: "BATATA INGLESA"
    unidade_comercial: "KG"
  - code: "41"
    description: "BATATA MIUDA"
    unidade_comercial: "KG"
  - code: "45"
    description: "BERINJELA"
    unidade_comercial: "KG"
  - code: "46"
    description: "BETERRABA"
    unidade_comercial: "KG"
  - code: "48"
    description: "CEBOLA BRANCA"
    unidade_comercial: "KG"
  - code: "47"
    description: "CEBOLA ROXA"
    unidade_comercial: "KG"
  - code: "13"
    description: "CEBOLINHA"
    unidade_comercial: "UN"
  - code: "49"
    description: "CENOURA"
    unidade_comercial: "KG"
  - code: "780"
    description: "CEREJA"
    unidade_comercial: "UN"
  - code: "112"
    description: "COCA COLA 2L RETOR"
    unidade_comercial: "UN"
  - code: "10"
    description: "COUVE"
    unidade_comercial: "UN"
  - code: "470"
    description: "COUVE KG"
    unidade_comercial: "KG"
  - code: "50"
    description: "CHUCHU"
    unidade_comercial: "KG"
  - code: "17"
    description: "HORTELA"
    unidade_comercial: "UN"
  - code: "54"
    description: "JILO"
    unidade_comercial: "KG"
  - code: "115"
    description: "KIWI"
    unidade_comercial: "KG"
  - code: "120"
    description: "LARANJA"
    unidade_comercial: "KG"
  - code: "127"
    description: "LIMAO"
    unidade_comercial: "KG"
  - code: "132"
    description: "LIMAO SICILIANO"
    unidade_comercial: "KG"
  - code: "141"
    description: "MACA FUJI"
    unidade_comercial: "KG"
  - code: "55"
    description: "MANDIOCA"
    unidade_comercial: "KG"
  - code: "146"
    description: "MANGA PALMER"
    unidade_comercial: "KG"
  - code: "19"
    description: "MANJERICAO"
    unidade_comercial: "UN"
  - code: "136"
    description: "MAMAO FORM"
    unidade_comercial: "KG"
  - code: "128"
    description: "MELANCIA"
    unidade_comercial: "KG"
  - code: "150"
    description: "MELAO"
    unidade_comercial: "KG"
  - code: "135"
    description: "MORANGO BANDEJA"
    unidade_comercial: "UN"
  - code: "66"
    description: "PENTE DE OVOS"
    unidade_comercial: "UN"
  - code: "76"
    description: "PEPINO"
    unidade_comercial: "KG"
  - code: "62"
    description: "PIMEN VL/AMAR"
    unidade_comercial: "KG"
  - code: "61"
    description: "PIMENTAO VERDE"
    unidade_comercial: "KG"
  - code: "65"
    description: "PRODUTOS EM PROMOCAO"
    unidade_comercial: "KG"
  - code: "78"
    description: "QUIABO"
    unidade_comercial: "KG"
  - code: "80"
    description: "REPOLHO ROXO"
    unidade_comercial: "KG"
  - code: "79"
    description: "REPOLHO VERDE"
    unidade_comercial: "KG"
  - code: "1124"  
    description: "SACO DE MILHO"
    unidade_comercial: "UN"  
  - code: "24"
    description: "SALSA"
    unidade_comercial: "UN"
  - code: "64"
    description: "TAXA DE ENTREGA"
    unidade_comercial: "UN"
  - code: "178"
    description: "UVA S/ SEMENTE"
    unidade_comercial: "UN"
  - code: "86"
    description: "VAGEM"
    unidade_comercial: "KG"
  - code: "81"
    description: "TOMATE"
    unidade_comercial: "KG"