products:
  - code: "135"
    description: "ALFACE"
    ncm: "07051100"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "3"
    description: "CEBOLINHA"
    ncm: "07039090"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "4"
    description: "SALSA"
    ncm: "07099990"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "49"
    description: "CEBOLA BRANCA"
    ncm: "07122000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "6"
    description: "PIMENTAO VERDE"
    ncm: "07096000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "9"
    description: "BATATA INGLESA"
    ncm: "07101000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "46"
    description: "BETERRABA"
    ncm: "07069000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "127"
    description: "LIMAO"
    ncm: "08055000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "87"
    description: "ABACAXI"
    ncm: "08043000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "76"
    description: "PEPINO"
    ncm: "20011000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "72"
    description: "PENTE DE OVOS BRANCOS"
    ncm: "04079000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "42"
    description: "BANANA CATURRA"
    ncm: "08031000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "55"
    description: "MANDIOCA"
    ncm: "07141000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "137"
    description: "MAMAO FORMOSA"
    ncm: "08072000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "120"
    description: "LARANJA"
    ncm: "08051000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "31"
    description: "ALHO SEM CASCA"
    ncm: "07032090"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "18"
    description: "VAGEM"
    ncm: "07082000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "144"
    description: "MANGA"
    ncm: "08045020"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "10"
    description: "COUVE"
    ncm: "07051100"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "48"
    description: "CHUCHU"
    ncm: "07101000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "62"
    description: "MELANCIA"
    ncm: "08071100"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "13"
    description: "HORTELA"
    ncm: "07099990"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "66"
    description: "MANJERICAO"
    ncm: "07099990"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "34"
    description: "ABOBORA ITALIANA"
    ncm: "07099300"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "142"
    description: "MACA FUJI"
    ncm: "08081000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "49"
    description: "CENOURA"
    ncm: "07101000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "79"
    description: "REPOLHO VERDE"
    ncm: "07051100"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "7"
    description: "ALMEIRAO"
    ncm: "07099090"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "81"
    description: "TOMATE"
    ncm: "07020000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "80"
    description: "REPOLHO ROXO"
    ncm: "07049010"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "3568"
    description: "AGUA MINERAL IG 20 LITROS"
    ncm: "22011000"
    cfop: "5405"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "150"
    description: "MELAO"
    ncm: "08071900"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "45"
    description: "BERINJELA"
    ncm: "07093000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "47"
    description: "CEBOLA ROXA"
    ncm: "07122000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "3118"
    description: "UVA SEM SEMENTE BANDEJA"
    ncm: "08061000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "37"
    description: "ABOBORA MORANGA"
    ncm: "07099300"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "1713"
    description: "HORTELA"
    ncm: "08107000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "78"
    description: "QUIABO"
    ncm: "07089000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "1854"
    description: "KIWI"
    ncm: "08105000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "135"
    description: "MORANGO BANDEJA"
    ncm: "08101000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "2011"
    description: "MANJERICAO"
    ncm: "07099990"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "62"
    description: "PIMENTAO VERMELHO E AMARELO"
    ncm: "07096000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "41"
    description: "BATATA MIUDA"
    ncm: "07101000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "160"
    description: "ALHO PORO"
    ncm: "07039010"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "43"
    description: "BATATA DOCE"
    ncm: "07101000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "43"
    description: "ALFACE CRESCA UN"
    ncm: "07051100"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "10"
    description: "COUVE UN"
    ncm: "07051100"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "142"
    description: "MACA FUJI"
    ncm: "08081000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "1877"
    description: "LARANJA SACO 10 KG"
    ncm: "08051000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "30"
    description: "ALHO COM CASCA"
    ncm: "07032090"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "1936"
    description: "LIMAO SICILIANO"
    ncm: "08055000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "295"
    description: "BANANA MACA"
    ncm: "08031000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "1127"
    description: "COCA COLA 2L RETORNAVEL"
    ncm: "22021000"
    cfop: "5405"
    icms: "6500"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"