products:
  - code: "135"
    description: "ALFACE"
    ncm: "07051100"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "3"
    description: "CEBOLINHA"
    ncm: "07039090"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "4"
    description: "SALSA"
    ncm: "07099990"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "49"
    description: "CEBOLA"
    ncm: "07122000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "6"
    description: "PIMENTAO"
    ncm: "07096000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "9"
    description: "BATATA"
    ncm: "07101000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "46"
    description: "BETERRABA"
    ncm: "07069000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "127"
    description: "LIMAO"
    ncm: "08055000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "87"
    description: "ABACAXI"
    ncm: "08043000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "76"
    description: "PEPINO"
    ncm: "20011000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "72"
    description: "PENTE DE OVO"
    ncm: "04079000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "42"
    description: "BANANA"
    ncm: "08031000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "55"
    description: "MANDIOCA"
    ncm: "07141000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "137"
    description: "MAMAO"
    ncm: "08072000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "120"
    description: "LARANJA"
    ncm: "08051000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "30"
    description: "ALHO SEM CASCA"
    ncm: "07032090"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "18"
    description: "VAGEM"
    ncm: "07082000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "82"
    description: "MANGA"
    ncm: "08045020"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "34"
    description: "COUVE"
    ncm: "07051100"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "48"
    description: "CHUCHU"
    ncm: "07101000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "62"
    description: "MELANCIA"
    ncm: "08071100"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "13"
    description: "HORTELA"
    ncm: "07099990"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "66"
    description: "MANJERICAO"
    ncm: "07099990"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "34"
    description: "ABOBRINHA"
    ncm: "07099300"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "142"
    description: "MACA FUJI"
    ncm: "08081000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "49"
    description: "CENOURA"
    ncm: "07101000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "79"
    description: "REPOLHO VERDE"
    ncm: "07051100"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "7"
    description: "ALMEIRAO"
    ncm: "07099090"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "81"
    description: "TOMATE"
    ncm: "07020000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "80"
    description: "REPOLHO ROKO"
    ncm: "07049010"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "3568"
    description: "AGUA_MINERAL_20L"
    ncm: "22011000"
    cfop: "5405"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"